### ISSUE TITLE
Cannot use Gradle dependency

### ISSUE THREAD

**Issue by LNDF** [riccardobl/v-hacd-java-bindings#2]
Bintray is no more available so Gradle/Maven dependency doesn't download correctly.

**Comment by riccardobl** [comment]
Hello. The artifacts is published also on github package registry
https://github.com/riccardobl/v-hacd-java-bindings/packages/710638

You can use it with the io.github.0ffz.github-packages plugin
```gradle
plugins {
    id "io.github.0ffz.github-packages" version "1.2.1"
}

repositories {
    maven githubPackage.invoke("riccardobl")
}

dependencies {
    compile 'vhacd:vhacd-native:1.1.2'
}
```
